apiVersion: apps/v1
kind: Deployment
metadata:
  name: empapp-deploy
spec:
  selector:
    matchLabels:
      app: empapp-service
  replicas: 2
  template:
    metadata:
      labels:
        app: empapp-service
    spec:
      containers:
      - name: empapp-service
        image: rgupta00/empapp:1.2
        ports:
        - name: "app-port"
          containerPort: 8080