apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: rgupta00/empapp:1.1
    imagePullPolicy: Always
    ports:
      - containerPort: 8080