kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30288
    hostPort: 30288
    protocol: TCP
  - containerPort: 30287
    hostPort: 30287
    protocol: TCP
- role: worker
- role: worker