apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: rgupta00/service-b
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30288

#  clusterIP: None # Headless service