apiVersion: apps/v1
kind: Deployment
metadata:
  name: empapp-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v1"
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app:  empapp-service
  replicas: 2
  template:
    metadata:
      labels:
        app:  empapp-service
    spec:
      containers:
      - name:  empapp-service
        image: rgupta00/empapp:1.1
        ports:
        - name: "app-port"
          containerPort: 8080
        readinessProbe:
            httpGet:
              path: /  # Adjust the path to your custom health endpoint
             # path: /actuator/health/readiness  # Adjust the path to your custom health endpoint
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
        livenessProbe:
            httpGet:
              path: /actuator/health/liveness  # Use the default health endpoint for liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
