apiVersion: apps/v1
kind: Deployment
metadata:
  name: empapp-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v3"
spec:
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app:  empapp-service
  replicas: 4
  template:
    metadata:
      labels:
        app:  empapp-service
    spec:
      containers:
      - name:  empapp-service
        image: rgupta00/empapp:1.3
        ports:
        - name: "app-port"
          containerPort: 8080